### ISSUE TITLE
start was working but how I can build?

### ISSUE THREAD

**Issue by dominicdev** [katungi/desktop-weather-app-demo#2]
I tried to start build but did not get any file for desktop

**Comment by katungi** [comment]
What do you mean any file? does it work when you build? Do you see anything when you build?

**Comment by dominicdev** [comment]
what do I need to see if I build also what is the command? I can build this like for exe file?

**Comment by katungi** [comment]
Hi @dominicdev , The article does not cover distribution or building for production. 
I would recommend you check the docs out.

https://www.electronjs.org/docs/tutorial/application-distribution

**Comment by dominicdev** [comment]
> Hi @dominicdev , The article does not cover distribution or building for production.
> I would recommend you check the docs out.
> 
> https://www.electronjs.org/docs/tutorial/application-distribution

thanks
